import mongoose from 'mongoose';

const spyGame = new mongoose.Schema({
  code:{type: Number, required: true, unique: true},
  gamestat:{ type:String, default:"waiting"},
  PlayerNum:{ type: Number, default: 3},
  SPYNum:{ type: Number, default: 1},
  chat:{type:String, default: "<p className='admin'>Waiting...<p>"},
  HostP1:{ type: String, required: true},
  p1stat:{ type:String, default: "none"},
  p1choosen:{type:String, default: "False"},
  p2:{ type: String, default:"waiting"},
  p2stat:{ type:String, default: "none"},
  p2choosen:{type:String, default: "False"},
  p3:{ type: String, default:"waiting"},
  p3stat:{ type:String, default: "none"},
  p3choosen:{type:String, default: "False"},
  p4:{ type: String, default:"none"},
  p4stat:{ type:String, default: "none"},
  p4choosen:{type:String, default: "False"},
  p5:{ type: String, default:"none"},
  p5stat:{ type:String, default: "none"},
  p5choosen:{type:String, default: "False"},
  p6:{ type: String, default:"none"},
  p6stat:{ type:String, default: "none"},
  p6choosen:{type:String, default: "False"},
  p7:{ type: String, default:"none"},
  p7stat:{ type:String, default: "none"},
  p7choosen:{type:String, default: "False"},
  p8:{ type: String, default:"none"},
  p8stat:{ type:String, default: "none"},
  p8choosen:{type:String, default: "False"},
  p9:{ type: String, default:"none"},
  p9stat:{ type:String, default: "none"},
  p9choosen:{type:String, default: "False"},
  p10:{ type: String, default:"none"},
  p10stat:{ type:String, default: "none"},
  p10choosen:{type:String, default: "False"},
  p11:{ type: String, default:"none"},
  p11stat:{ type:String, default: "none"},
  p11choosen:{type:String, default: "False"},
  p12:{ type: String, default:"none"},
  p12stat:{ type:String, default: "none"},
  p12choosen:{type:String, default: "False"}
});

export default mongoose.model('Game', spyGame);